name: Release
on:
  push: 
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            backend:
                - 'src/backend/**/*'
            frontend:
                - 'src/frontend/**/*'

  backend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/kosh-server
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/backend/

      - name: Deploy to k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_PROD }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_KEY }}
          script: |
            ./autodeploy_kosh_rest.sh ${{ steps.vars.outputs.sha_short }} >> ~/deploy.log 2>&1

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Kosh to production environment"
          SLACK_TITLE: "staging-production workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg

  frontend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Install Packages
        run: |
          cd src/frontend 
          npm install --legacy-peer-deps

      - name: Build Site
        run: |
          cd src/frontend 
          npm run build
      - name: Deploy Site
        run: |
          cd src/frontend 
          npm run deploy

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Kosh Frontend to production environment"
          SLACK_TITLE: "Deploy Kosh Frontend Workflow Complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg
